{% set goname = "github.com/tianon/gosu" %}
{% set version = "1.15" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = 'src/'+goname %}

# The runc version much match the upstream Dockerfile
# https://github.com/tianon/gosu/blob/master/Dockerfile
{% set runc_goname = "github.com/opencontainers/runc" %}
{% set runc_version = "1.1.0" %}
{% set runc_pkg_src = 'src/'+runc_goname %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: b989523bb30ed4b026cea978b6093931cbce2bcca72bad3d051b928987c89d46

  - folder: {{ runc_pkg_src }}
    url: https://{{ runc_goname }}/archive/v{{ runc_version }}.tar.gz
    sha256: a8de57edbf0ff741ea798ccdd99ac0e1b79914f552871bd7cd92b0569f200964

build:
  number: 0
  skip: true  # [not linux]
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags '-d -s -w'
    - go test -v

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - which gosu
    - test -x $PREFIX/bin/gosu
    - gosu --version

    # These require root to test
    # - gosu nobody id;
    # - gosu nobody ls -l /proc/self/fd

about:
  home: https://github.com/tianon/gosu
  license: Apache-2.0
  license_file: src/github.com/tianon/gosu/LICENSE
  summary: Simple Go-based setuid+setgid+setgroups+exec

  description: |
    This is a simple tool grown out of the simple fact that `su` and `sudo`
    have very strange and often annoying TTY and signal-forwarding behavior.
    They're also somewhat complex to setup and use (especially in the case of
    `sudo`), which allows for a great deal of expressivity, but falls flat if
    all you need is "run this specific application as this specific user and
    get out of the pipeline".
  dev_url: https://github.com/tianon/gosu
  doc_url: https://github.com/tianon/gosu

extra:
  recipe-maintainers:
    - jakirkham
    - sodre
