{% set goname = "github.com/tianon/gosu" %}
{% set version = "1.11" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = 'src/'+goname %}

# The runc version much match the upstream Dockerfile
# https://github.com/tianon/gosu/blob/master/Dockerfile
{% set runc_goname = "github.com/opencontainers/runc" %}
{% set runc_version = "1.0.0-rc5" %}
{% set runc_pkg_src = 'src/'+runc_goname %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: d03208fd7ef983e4a606f861a5efcdc5a1980952a91febba3f67057800da6701

  - folder: {{ runc_pkg_src }}
    url: https://{{ runc_goname }}/archive/v{{ runc_version }}.tar.gz
    sha256: 770e180d1cca1f3c1a67512ebf9720caafe97af4fc2fe12fa43a3cf7bfa77522

build:
  number: 1000
  skip: true  # [not linux]
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags '-d -s -w'
    - go test -v

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - which gosu
    - test -x $PREFIX/bin/gosu
    - gosu --version

    # These require root to test
    # - gosu nobody id;
    # - gosu nobody ls -l /proc/self/fd

about:
  home: https://github.com/tianon/gosu
  license: GPL-3.0-or-later
  license_file: src/github.com/tianon/gosu/LICENSE
  summary: Simple Go-based setuid+setgid+setgroups+exec

  description: |
    This is a simple tool grown out of the simple fact that `su` and `sudo`
    have very strange and often annoying TTY and signal-forwarding behavior.
    They're also somewhat complex to setup and use (especially in the case of
    `sudo`), which allows for a great deal of expressivity, but falls flat if
    all you need is "run this specific application as this specific user and
    get out of the pipeline".
  dev_url: https://github.com/tianon/gosu
  doc_url: https://github.com/tianon/gosu

extra:
  recipe-maintainers:
    - jakirkham
    - sodre
