appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XN5wGFhD/GXeC0LwUvTsawGjT1ayIh2ygF15YgEkU3W9HVDYmydx3ijrFWq9rDdAgg8XLXFTxMo9m+goCnbY6iXX6oPHPDwSEuSn0bxcPI5y5InChhFeYK4uZSTKLWrTBfJqtgT6GTDjSUBbJf/mW/QIDMg6r5zBW5umDY4+wbruEVH1SnGhAJEMNTXaUudidK0evxrr8+8J9FrVQNg6HUrA/8Hx8GmdXfgHuzP3MQolig0qgI2ISyVhToO8vxaKYVppSFibbEDpZIyJNGyGPEm1h1+ZbBOWg7X4annpQ7xwJdyNOrS5l/MdjRLWMEtbPFXkDe/lSH4GtL3asPSwAtjS7wxyVRouS9cKd5JWShLlvX3GidOaNH1JQ+mlP1ajScczQcW0hDHXfuOf0hIPI9Q442cW1ycxGtKmKrkSOdGU2Qctf/EbQyAXYfenDo2daKmcsS1Q+7PzMEKcxP9xwxvJ/V9NP0vGFQeie2ZvLouBsVbRgde+FBKUIzwrz5n+9ULrDrRL4sqvevLzqFi9mUYch9cI5FR9zdMHR3NGSFC/uwsOOAoUAcB3EnkCqQDJtod+o7GN/or6nZf5San1aN7q64kbeZQsx0uSSY8YFg2DZaAleahZy2l6nRLWnTdM2lvFZgcC8BOTKk7Tacc3kLBMMwVQzIV8Re7Tnc0taQA=}
conda_forge_output_validation: true
